spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: studyspringcloud-config-dev

---
spring:
  profiles: test
  application:
    name: studyspringcloud-config-test