spring:
  profiles:
    active:
    - dev

---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: studyspringcloud-config-dev
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost-dev:7001/eureka


---
server:
  port: 8082
spring:
  profiles: test
  application:
    name: studyspringcloud-config-test

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost-test:7001/eureka
